### ISSUE TITLE
Header does not display

### ISSUE THREAD

**Issue by Syriuss** [pscj/android-datagridview#1]
Hi,

I trying to use your sample app, but the grid header does not displayed even if I set the show header flag to true. 
`dataGridView.setData(result, true);`
Could you help me how to display it?

I using Android 7.1. As I see the visibleLine in line 267 of CustomDataGrid.java is 0. Is something compatibility issue?

Thank you!
Syrius

**Comment by pscj** [comment]
do you have change somethings about build.gradle, ex. gradle version,compileSdkVersion, or something else?

**Comment by Syriuss** [comment]
Hi,

Yes, I changed target SDK to Api 24.
This colud cause this issue?

谢谢,
Syrius

pscj <notifications@github.com> ezt írta (időpont: 2018. máj. 14., H 10:25):

**Comment by pscj** [comment]
我看现在代码targetSdkVersion就是24啊

**Comment by Syriuss** [comment]
Yes, it is. Then I changed it an upper (Api 27) and back to 24.
Now I restarted from scratch, cloned your repo and open in IDE. But I forgot to tell you that I using Android Studio 3.1.2 and it upgraded Glade version:

> To take advantage of all the latest features (such as Instant Run), improvements and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.1.2 and Gradle to version 4.4.

I can't run the project without this upgrade. It asked me in Edit Module settings to select target SDK but I can't.
And report in glade files tells that the compile is deprecated and replaced with api and implementation.

谢谢,
Syrius
![kepernyokep errol 2018-05-14 11-30-16](https://user-images.githubusercontent.com/6184775/39989457-4314a5fc-576a-11e8-8d18-0d882fc3a284.png)

**Comment by Syriuss** [comment]
Now we had to move to Marsmallow and it now works as expected.
Is that possible to add a checkbox to the first column?

谢谢,
Syrius

**Comment by pscj** [comment]
two solutions
1. draw a checkbox to the column, you should draw a rectange and draw text on the right
2. draw a image to the column, a image looks like a checkbox, actually two images are required,  a checked,and a unchecked

**Comment by sajjadali118** [comment]
Check your current theme. Issue is with the theme. 
use parent="@style/Theme.AppCompat.DayNight" for your apptheme.
